# Generated by Django 3.0.7 on 2021-12-18 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_comp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contact'},
        ),
    ]
