# Generated by Django 3.0.7 on 2021-12-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20211218_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(max_length=55500, verbose_name='Caption'),
        ),
    ]
