# Generated by Django 3.0.7 on 2021-12-29 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20211229_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comp',
        ),
    ]
