# Generated by Django 3.0.7 on 2021-12-29 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='achivement',
        ),
    ]
